package pl.edu.pjatk.tau.dao;

import pl.edu.pjatk.tau.domain.Book;

import java.sql.*;

public class BookDaoJdbcImpl implements BookDao {

    private Connection connection;
    private PreparedStatement addBookStmt;


    public BookDaoJdbcImpl() throws SQLException {
    }

    public BookDaoJdbcImpl(Connection connection) throws SQLException {
        this.connection = connection;
        // if (!isDatabaseReady()) {
        //    createTables();
        //}

        setConnection(connection);
    }

    public void createTables() throws SQLException {
        connection.createStatement()
                .executeUpdate("CREATE TABLE " +
                        "Book" +
                        "(id bigint GENERATED BY DEFAULT AS IDENTITY, " +
                        "title varchar(20) NOT NULL," +
                        "year integer)");
    }

    private boolean isDatabaseReady() {
        try {
            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Book".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }
            return tableExists;
        } catch (SQLException e) {
            return false;
        }
    }

    @Override
    public int addBook(Book book) {
        int count = 0;
        try {
            addBookStmt.setString(1, book.getTitle());
            addBookStmt.setInt(2, book.getYear());
            count = addBookStmt.executeUpdate();
            ResultSet generatedKeys = addBookStmt.getGeneratedKeys();
            if (generatedKeys.next()) {
                Book.setId(generatedKeys.getLong(1));
            }
        } catch (SQLException e) {
            throw new IllegalStateException(e.getMessage() + "\n" + e.getStackTrace().toString());
        }
        return count;
    }

    @Override
    public Connection getConnection() {
        return connection;
    }

    @Override
    public void setConnection(Connection connection) throws SQLException {
        this.connection = connection;
        addBookStmt = connection.prepareStatement(
                "INSERT INTO Book(title, year) VALUES (?, ?)",
                Statement.RETURN_GENERATED_KEYS);
    }
}